### ISSUE TITLE
Tag-110- The invalid Definition_Review_Date Can be Saved

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#124]
When adding or modifying the Definition for a class, if you modify this correct date format "2016-12-11" to an invalid date format "2016-1267788-11 then you save it . 
Please see attached zip file to play the video clip. 
Regards,
Reza

[Invalid Definition_Review_Date.zip](https://github.com/NCIEVS/nci-protege5/files/645108/Invalid.Definition_Review_Date.zip)

**Comment by YinghuaXu2** [comment]
Fixed in https://github.com/bdionne/nci-edit-tab/commit/ccd4c97ffb4f040d11c8144f185b374c5689fbde

**Comment by rmehri** [comment]
This fix has been retested and verified that the same issue still exists. Please see attached snapshot for more detail. 
Thanks,
Reza
![untitled](https://cloud.githubusercontent.com/assets/8367102/21661023/15cee724-d2a0-11e6-861a-9cc3bb761be7.png)

**Comment by bdionne** [comment]
The reviewer name and the date should be set and made read only. Users should not be allowed to edit these fields
