### ISSUE TITLE
Tag-112-NCI Edit Tab-NCI AQ and NCI HD should be equal to NCI PT

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#138]
Steps to reproduce:
1.Launch server and client
2.Log into local host http://localhost:8080
3.Use "Reza" Work Flow Modeler
4.Select NCI Edit Tab 
5.Create a new OWL Class with Preferred Name: BDA Testing NCI PT save it then  
6.Add complex property  (Full _SYN) and add values and term source=NCI and AQ  
7. You'll see the warning message and won't add it.

Note: Please see this requirement: https://wiki.nci.nih.gov/display/EVS/Business+Rules+for+Editing+NCI+Thesaurus
Please attached zip file to play the video.

Thanks,
 Reza

[NCI PT Equivalency-1.zip](https://github.com/NCIEVS/nci-protege5/files/661865/NCI.PT.Equivalency-1.zip)

**Comment by bdionne** [comment]
[fixed](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.2)

**Comment by rmehri** [comment]
I have retested this fix and verified that the same issue still exists.  Please see attached snapshots for more details. 
Thanks,
Reza

![tag-115-full_sy_nci-hd](https://cloud.githubusercontent.com/assets/8367102/21649360/729b045a-d26f-11e6-9cd5-c664b067ac7f.png)

![tag-115-full_sy_nci-aq](https://cloud.githubusercontent.com/assets/8367102/21649379/85d0535e-d26f-11e6-9e15-4815aa42aeaf.png)

**Comment by bdionne** [comment]
From the screenshot, it looks like you do not have defaults for the qualifiers set. The error message read "One and only one..." which I think is the correct behavior in this case. You need to have at least one `FULL_SYN` with source `NCI` and type `PT`

**Comment by rmehri** [comment]
But based on the following requirement, there should only one of these  "NCI PT (or HD or AQ) 
•FULL_SYN •One and only one NCI|PT (or HD or AQ) FULL_SYN must exist • 
Please clarify. 
Thanks,
Reza

**Comment by bdionne** [comment]
yes that's correct

**Comment by rmehri** [comment]
Based on requirement and development's comment.  This ticket can be closed.
