### ISSUE TITLE
Save button not behaving correctly

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#22]
The interaction with the presence of the classes tab is problematic. 

When any change occurs in `EditTab` to the current selected class, the save button should be enabled

If the user navigates away from the `EditTab` they should be warned, and if they wish to continue, all changes should be cleared out

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.112)

**Comment by rmehri** [comment]
Hi Bob, 
Based on description of this ticket, should a user expect a warning message before exiting the class editing page? Or just expect the same "Save" and "Clear" buttons?

Also, I have extended my testing, here is the test:
On NCI Edit Tab, selected activity-foo,
1)	Add definition with value= activity-foo-test, def source= ACC and clicked Ok
2)	The “Save” and “Clear” buttons are displayed
3)	Do not Save or clear
4)	Click Edit link and select Create Child with the name: activity-foo-test1
5)	The activity-foo editing) is displayed.
6)	Select Save and both “activity-foo-test” & “activity-foo-test1” are saved successfully.
7)	I did not see any warning message to prevent me to add a child class before saving activity-foo-test!
Please see attached zip file to play the video for more details.
Thanks,
Reza

[Edit Tab-Save.zip](https://github.com/NCIEVS/nci-protege5/files/664449/Edit.Tab-Save.zip)

**Comment by bdionne** [comment]
you should see warning messages [now](https://github.com/bdionne/nci-edit-tab/releases/tag/nci-edit-tab-0.2.3) in that scenario.

**Comment by rmehri** [comment]
I retested this fix using tag-112, =NCI Edit Tab 0.23,  here in my test:
On NCI Edit Tab, selected activity-bar6
1.Added definition with value= activity-bar6-test1, def source= NCI and clicked Ok
2.The “Save” and “Clear” buttons are displayed.
3. I did not select an table rows
4.Clicked Edit link and tried to select Create Child but noticed all these links greyed out (Create New, Create Child and Create Sibling)?  --> Not sure if this is the expectation?
5. When I selected table definition row and all these links became active:(Create New, Create Child and Create Sibling) then,
6. Selected Create Child from step#5 and received the warning message. 
7. Clicked Ok and did not select save or clear then,
8. Selected Create New and the java error occurred ===> (Java Error)
Please see attached zip file to play the video clip and log file for more details.

Thanks,
Reza
[Edit Tab-023-Warning Message.zip](https://github.com/NCIEVS/nci-protege5/files/667064/Edit.Tab-023-Warning.Message.zip)

**Comment by rmehri** [comment]
I have retested this issue and verified that the same problem still exits using tag-115.

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - please enumerate the steps to reproduce this, I'm pretty sure this was fixed. As I mentioned before the `create child` menu item will eventually be disabled The correct way to create a new class is to use the icon in the navigation pane

**Comment by rmehri** [comment]
The issue is not fully resolved.  The following links should be greyed out while the save action not completed for creating a child. Currently, when selecting any of those links causes java errors. 
Please see attached screen shot for more detail. 
1) Create New 
2) Create Sibling 
*Note: this ticket will remain open until they are resolved.

Also, please use the same previous steps to reproduce: 

 1.Added definition with value= activity-bar6-test1, def source= NCI and clicked Ok
 2.The “Save” and “Clear” buttons are displayed.
 3. I did not select an table rows
 4.Clicked Edit link and tried to select Create Child but noticed all these links greyed out (Create New, Create Child and Create Sibling)? --> Not sure if this is the expectation?
 5. When I selected table definition row and all these links became active:(Create New, Create Child and Create Sibling) then,
 6. Selected Create Child from step#5 and received the warning message.
 7. Clicked Ok and did not select save or clear then,
 8. Selected Create New and the java error occurred ===> (Java Error) See new issue #142
 Please see attached zip file to play the video clip and log file for more details.

Thanks,
Reza



![create child](https://cloud.githubusercontent.com/assets/8367102/21690231/5d981976-d341-11e6-861a-238cbf13fa95.png)

**Comment by bdionne** [comment]
@rmehri - sorry I'm completely confused as to what the problem is you are referring to. As I mentioned, using the protege menu items to create classes is incorrect. They will eventually be removed and/or disabled.

Please open a new ticket if needed and enumerate what the problem is, the steps to reproduce it, and the behavior you see as well as the behavior you expect to see.
