### ISSUE TITLE
Auto-Update of Plugins in Protege Client does not overwrite the older versions 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#406]
When an auto-update for a Plugin is selected , the updated Plugin versions do not overwrite the older versions in 'plugin' folder for Protege Client, which leaves both old and new versions in the configuration.

This is temporarily  resolved by manually deleting the older version from configuration and then restart of Protege .
Need to have the auto-update  subroutine overwrite the older versions automatically ....

**Comment by NCIEVS** [comment]
console output exception on plugin update

←[34mAuto-update last performed: Fri Sep 21 13:41:55 EDT 2018←[0;39m
←[34mAuto-update has been performed today.  Not performing it again.←[0;39m
←[34m←[0;39m
←[34m------------------------------ Running Auto-update -----------------------------←[0;39m
←[34m←[0;39m
←[34m--- Searching for plugins ---←[0;39m
←[34mChecking https://raw.githubusercontent.com/bdionne/autoupdate/master/plugins.repository←[0;39m
←[34m    Processing https://raw.githubusercontent.com/bdionne/autoupdate/master/plugins.repository as a plugin registry←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/nci-edit-tab/master/src/main/resources/update.properties←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/lucene-search-tab/master/src/main/resources/update.properties←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/metaproject-admin/master/src/main/resources/update.properties←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/revision-history/master/src/main/resources/update.properties←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/sparql-query-plugin/master/src/main/resources/update.properties←[0;39m
←[34m        Checking https://raw.githubusercontent.com/ncievs/evs-history/master/src/main/resources/update.properties←[0;39m
←[34m←[0;39m
←[34m----------------------- Downloading and Installing Plugin ----------------------←[0;39m
←[34mDownloading the NCI Edit Tab plugin (Version 0.9.3)←[0;39m
←[34mDownloading the NCI Edit Tab plugin from: https://github.com/ncievs/nci-edit-tab/releases/download/nci-edit-tab-0.9.3/nci-edit-tab-0.9.3-SNAPSHOT.jar←[0;39m
←[34mThe NCI Edit Tab plugin has been downloaded to O:\Users\fragosog\LOCALS~1\Temp\41\nci-edit-tab8773559124302216103.jar←[0;39m
java.nio.file.FileSystemException: O:\Users\fragosog\Desktop\nci-protege-V2.5.5\plugins\nci-edit-tab-0.9.2.jar -> O:\Users\fragosog\Desktop\nci-protege-V2.5.5\plugins\nci-edit-tab-0.9.2.jar.
old: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.nio.file.Files.move(Unknown Source)
        at org.protege.editor.core.update.PluginInstaller.moveExistingPluginToBackupLocation(PluginInstaller.java:183)
        at org.protege.editor.core.update.PluginInstaller.copyPluginToInstallLocation(PluginInstaller.java:195)
        at org.protege.editor.core.update.PluginInstaller.install(PluginInstaller.java:104)
        at org.protege.editor.core.update.PluginInstaller.lambda$run$0(PluginInstaller.java:63)
        at java.lang.Thread.run(Unknown Source)
←[34mCopied the NCI Edit Tab plugin to nci-edit-tab-0.9.3.jar in the plugins directory←[0;39m
←[34mThe NCI Edit Tab plugin requires a restart of Prot├⌐g├⌐←[0;39m
←[34m←[0;39m
←[34m----------------------- Downloading and Installing Plugin ----------------------←[0;39m
←[34mDownloading the NCI Lucene Search Tab plugin (Version 1.1.9)←[0;39m
←[34mDownloading the NCI Lucene Search Tab plugin from: https://github.com/ncievs/lucene-search-tab/releases/download/lucene-search-tab-1.1.9/lucene-search-tab-1.1.9-SNAPSHOT.jar←[0;39m
←[34mThe NCI Lucene Search Tab plugin has been downloaded to O:\Users\fragosog\LOCALS~1\Temp\41\lucene-search-tab1241901687254239294.jar←[0;39m
java.nio.file.FileSystemException: O:\Users\fragosog\Desktop\nci-protege-V2.5.5\plugins\lucene-search-tab-1.1.8.jar -> O:\Users\fragosog\Desktop\nci-protege-V2.5.5\plugins\lucene-search-tab-
1.1.8.jar.old: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.nio.file.Files.move(Unknown Source)
        at org.protege.editor.core.update.PluginInstaller.moveExistingPluginToBackupLocation(PluginInstaller.java:183)
        at org.protege.editor.core.update.PluginInstaller.copyPluginToInstallLocation(PluginInstaller.java:195)
        at org.protege.editor.core.update.PluginInstaller.install(PluginInstaller.java:104)
        at org.protege.editor.core.update.PluginInstaller.lambda$run$0(PluginInstaller.java:63)
        at java.lang.Thread.run(Unknown Source)
←[34mCopied the NCI Lucene Search Tab plugin to lucene-search-tab-1.1.9.jar in the plugins directory←[0;39m
←[34mThe NCI Lucene Search Tab plugin requires a restart of Prot├⌐g├⌐←[0;39m
←[34m←[0;39m

**Comment by singhik** [comment]
@bdionne : Hi Bob, Plugins folder **do not** get overwritten with updated new versions , rather old and new versions are both present post update. Attached is the word document with screen print for reference .....
[Issue 406.docx](https://github.com/NCIEVS/nci-protege5/files/2765507/Issue.406.docx)

**Comment by bdionne** [comment]
Is fixed in next build

**Comment by singhik** [comment]
@bdionne : Hello,  This issue still exists in Protege 3.1.0 client , Auto Update plugin does not get overwritten but instead has multiple instances under plugin folder .

Before Auto Update :: 

![image](https://user-images.githubusercontent.com/36314371/58065483-dce4e080-7b53-11e9-9859-bc857eac0dfd.png)


After Auto Update of f.e. 'pellet-protege' plugin :: 

![image](https://user-images.githubusercontent.com/36314371/58065529-0e5dac00-7b54-11e9-9a37-cc63bb2cef7f.png)

![image](https://user-images.githubusercontent.com/36314371/58065569-3220f200-7b54-11e9-8f70-7a2681abfd28.png)

![image](https://user-images.githubusercontent.com/36314371/58065588-4238d180-7b54-11e9-9886-3d07ac95cf7c.png)

**Comment by bdionne** [comment]
this is interesting, it's working here fine. It will fail if the "-SNAPSHOT" version of a jar was installed but I downloaded the packaged client and it has the correct "pellet-protege-2.4.5.jar" bundled in there.

@NCIEVS and @safrant do you also see this fail when you update from 2.4.6? 

@singhik did you check the directory after you did the restart? You won't see it deleted right away, because it could be already loaded and the delete might fail. That's why we moved the delete step to occur when you do the restart and it's loading the plugins.

**Comment by NCIEVS** [comment]
@bdionne, yes, in windows/remote apps I had to manually delete the older pellet jar in 3.1.0 QA.  

I've just done an install of 3.1.0 QA in my linux desktop and the autoupdate of pellet to 2.4.6 went fine, the older 2.4.5 got replaced.

**Comment by bdionne** [comment]
I wonder if this is Windows or remote apps?

**Comment by NCIEVS** [comment]
Yeah, I can't say.  But remote apps should be "neutral" and just do whatever windows wants.  Maybe @safrant  will get a windows VM or laptop to confirm these cases.

**Comment by bdionne** [comment]
could be the windows version, I know it works on Yinghua's surface laptop, I'll find out the version

**Comment by NCIEVS** [comment]
OK.  We have windows server 2012 on remote apps.  I believe @singhik has windows 10.

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hello, 
1. Yes, both versions remained after my restart as well .Did not get overwritten.
2. Yes, I am on Windows 10 .

**Comment by bdionne** [comment]
We're also using Windows 10

**Comment by bdionne** [comment]
oops, didn't mean to close this, we're still trying to determine why it fails on Windows 10. It works on Windows 10 when run from Eclipse, so maybe there's an issue with how it's packaged. It's dependent on the contents of the manifest.

When protege loads it builds the classpath dynamically from the plugins. It hashes the names as it goes along and if it encounters a name already in the hash it deletes that version.

**Comment by bdionne** [comment]
This looks to be a windows issue:

https://stackoverflow.com/questions/4179145/release-java-file-lock-in-windows

We'll figure out a workaround

**Comment by singhik** [comment]
@safrant : Can you please send the bat file for removing old plugins for Windows ....

**Comment by singhik** [comment]
@bdionne :: Hello Bob,  Have added 'removeOldPlugins.bat'  file and did auto-update , but the Old plugins remain and does not get  removed/overwritten with new plugin  on Windows ....

**Comment by singhik** [comment]
@NCIEVS : Hello, As this issue is not fixed and is intermittent in Windows with low priority, we can move it from 3.1.0 Milestone to subsequent next Release ....

**Comment by NCIEVS** [comment]
Agree with @singhik.

**Comment by NCIEVS** [comment]
In 3.3.0 (dev3 and -QA1) the plugin update doesn't clean up the older plugin.  The oldPlugins.txt file is not being written out and is missing.  (This file contain the list of plugins to delete on restart with removeOldPlugins.bat).

**Comment by bdionne** [comment]
We found a bug with this, where if you've loaded plugins outside the autoupdate mechanism it doesn't clean up correctly

**Comment by bdionne** [comment]
fixed in tag [3.6.0-dev3](https://github.com/NCIEVS/protege/tree/3.6.0-dev3)

**Comment by NCIEVS** [comment]
Changes are in commit [b89d8003261](https://github.com/NCIEVS/protege/commit/b89d8003261b3a1b08e30449adb6c88fb8415227).

**Comment by singhik** [comment]
@bdionne : Hi, it's still reproducible and the older plugins jar do not get overwritten by the updates  on 3.6.0-dev7 ::

![image](https://user-images.githubusercontent.com/36314371/120368496-238f7880-c2e0-11eb-97b0-1b4e535747ef.png)

**Comment by NCIEVS** [comment]
Hi @singhik , it seems that you closed this one accidentally, yes?  Did you check to see if the deletion happened after the restart of protege?

**Comment by singhik** [comment]
@NCIEVS : Hi, nope, it was closed post verification and intentionally, i did verify the overwriting of new plugin jars over old ones. Attached is the screen print document for your reference ....
[Issue_406.docx](https://github.com/NCIEVS/nci-protege5/files/6580097/Issue_406.docx)

**Comment by singhik** [comment]
@NCIEVS : Sure, Thanks
