### ISSUE TITLE
Copy behavior in complex property table changed

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#597]
In the current production version, modelers can `Ctrl-C` and copy to the clipboard on rows in the complex property tables. When they paste in other tools only the property value is copied.

In the new `4.4.0-dev10` release the entire row of qualifiers gets copied along with spaces and special characters.

**Comment by bdionne** [comment]
This is fixed in [EditTab-1.5.9](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.5.9)

**Comment by singhik** [comment]
@bdionne : To look at the implementation and review the changes

**Comment by bdionne** [comment]
@singhik, this is working as intended, and is also the way it works in production. The bug, which Liz found in the prior release they tested was that the default had changed and `Ctl-C` was copying the entire row from the table

**Comment by singhik** [comment]
4.4.1 Milestone build has the CTRL +C  copying only the 'value' of the Complex Properties instead of the whole table row. This has been QA Verified .

**Comment by singhik** [comment]
From Editors ::
This bugfix was not applied the way I thought the editors requested. 
Currently in protégé-4.3.0, the qualifier values aren’t copied to the clipboard but the tabs between the qualifiers are copied as empty spaces. 
Our request was to be able to just get the property value using Ctrl-C to copy to the clipboard, and NOT the qualifiers and NOT the empty tabs for each qualifier column.

P.S. Here’s the current behavior (with screenshots):

1.	Select multiple FULL_SYN in protégé
 
2.	Hit Ctrl-C
3.	Paste into a text editor (with all characters shown)
 

<img width="373" height="79" alt="Image" src="https://github.com/user-attachments/assets/d5922535-83cb-411d-a419-dbdf2a450a3f" />

How we want #3 to look in the future:

<img width="332" height="104" alt="Image" src="https://github.com/user-attachments/assets/7f8ee0d1-5dfe-41f7-81bf-6c0861db1923" />

**Comment by bdionne** [comment]
@singhik I believe this works as intended. Please check it and make sure it isn't a Max/Windows issue. I'm running EditTab 1.6.2

**Comment by singhik** [comment]
@bdionne  : Hi Bob, it is not, i see spaces are getting copied with values too : Edit Tab plugin is 1.6.2 : 

<img width="959" height="563" alt="Image" src="https://github.com/user-attachments/assets/1aec308f-961d-4e0b-a908-ef7717fe7460" />

<img width="1920" height="1128" alt="Image" src="https://github.com/user-attachments/assets/25f5fc44-6584-49f1-8cd3-ceeb9afcfdc2" />

**Comment by bdionne** [comment]
Is this 4.4.1-dev3 @singhik ?

Does it copy the tabs if you just select 1 row, and not several as you have in the screenshot?

**Comment by singhik** [comment]
@bdionne  : Yes, 4.4.1-dev3 build . When only one row is copied then no other tabs are copied : 

<img width="368" height="129" alt="Image" src="https://github.com/user-attachments/assets/ed608f76-0e48-4463-80c2-27f866b62009" />

**Comment by bdionne** [comment]
I see, so they want multiple rows and not just one. I can probably change this. This was actually the default in JTable before and then it changed, I suspect due to new components interacting with it. I'll have to write a CopyToClipboard action handler to get this intended behavior.

Thanks @singhik !

**Comment by bdionne** [comment]
This is [fixed in edit tab 1.6.3](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.6.3), @singhik you can give it a try.

**Comment by singhik** [comment]
@bdionne  : It is still reproducible in NCI Edit 1.6.3 : 

<img width="959" height="565" alt="Image" src="https://github.com/user-attachments/assets/69412b71-467f-422c-a1e1-b8ae82ea5f1a" />

<img width="398" height="136" alt="Image" src="https://github.com/user-attachments/assets/79e4a638-a33d-4fd2-abc6-d930142112f0" />

**Comment by bdionne** [comment]
@singhik , interesting, perhaps you can step through it today when we meet for status. I'd like to see the steps you take as I don't see this. Hopefully it's not a windows/Mac issue.

**Comment by bdionne** [comment]
@singhik ok, this turns out to be easy to reproduce:

 - open the project
 - enable and select focus to the sparql plugin tab
 - return to edit tab and see that the Ctrl-C copy to the clipboard action fails

**Comment by bdionne** [comment]
This is fixed in [1.6.4](https://github.com/NCIEVS/nci-edit-tab/releases/tag/nci-edit-tab-1.6.4)

**Comment by singhik** [comment]
Verified in 1.6.4 , works as expected.

<img width="482" height="161" alt="Image" src="https://github.com/user-attachments/assets/086f8116-82dd-42f7-94aa-667641fd7cc5" />

**Comment by bdionne** [comment]
Users want a slight difference in the behavior. When only one record is selected for Ctl-C do NOT add a line terminator at end ("\n" on unix, "/r/n" on windows)

**Comment by singhik** [comment]
4.4.1-dev3 build, 1.6.6 NCI Edit Tab :

**When multiple rows are copied, Line terminator is added post CTRL +C :** 

<img width="602" height="92" alt="Image" src="https://github.com/user-attachments/assets/ed5cb9e6-bac7-4706-9a8b-c06be17c5c89" />

<img width="280" height="82" alt="Image" src="https://github.com/user-attachments/assets/1d995735-fc50-4589-8d19-e8ff4a89f330" />

**When Single row is copied, Line Terminator is NOT added post CTRL+C :** 

<img width="298" height="56" alt="Image" src="https://github.com/user-attachments/assets/0d298c1e-c200-42e1-9828-2f02f15abfa3" />

<img width="410" height="70" alt="Image" src="https://github.com/user-attachments/assets/829231f9-62ac-4382-9d93-c5a96963c419" />
