### ISSUE TITLE
some class names show up in blue in the tree widget and other locations

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#84]
these happen to match a keyword, for example "domain" and "range"

**Comment by bdionne** [comment]
can be fixed if needed

**Comment by NCIEVS** [comment]
highlighted entities show up in the tree widget if the class is named exactly like a keyword, e.g. And is not highlighted but and is highlighted.  If part of a name, e.g. 'head and neck', the and is not highlighted either in the tree widget or when the class is used in a restriction filler.

**Comment by bdionne** [comment]
It turns out `renderToken` in `OWLCellRenderer` also takes the `EntityType` as an argument, which can be checked to [prevent this](https://github.com/NCIEVS/protege/commit/b831a0a58aaa521596)

**Comment by singhik** [comment]
@bdionne  : I still see blue color on concepts with key names , below is the screen print : 

![image](https://user-images.githubusercontent.com/36314371/162085173-b1acb757-c318-4210-978a-c893d7727773.png)

**Comment by bdionne** [comment]
@NCIEVS 

We might want to wait on fixing this one it's another edge case. I know how to fix it but it will require another protege build and likely not worth it given we've lived this long with it.

@singhik is it fixed in the navigation pane?

**Comment by singhik** [comment]
@bdionne  : Yes, it works for Navigation hierachy pane as it does not display concepts with special color(s) or links . Retire operations and related display(s) are the ones where it fails and still displays color control concepts .

**Comment by singhik** [comment]
@bdionne @NCIEVS  : As per Team discussion on 4/14, this ticket will be closed with the fix working and applicable for Concept Navigation Pane, for other panels like Retire, this issue still persists and can be looked in future as applicable .

**Comment by NCIEVS** [comment]
@bdionne @singhik , while going over the client configuration for the automated config process, I remembered I once looked at the "keywords" options, below, and then obviously forgot about it:

![image](https://user-images.githubusercontent.com/7783321/163860540-381db9a1-c1c2-4351-8a8f-7e30ff7982b5.png)

Here's how the retirement usage panel looks like with the above config:

![image](https://user-images.githubusercontent.com/7783321/163860290-d3c75cea-6aa1-443b-b361-eaa984570529.png)

We may not have had to do anything on this ticket!

**Comment by bdionne** [comment]
@NCIEVS - the downside of that is it also removes them from the descriptions, and when you edit textual representations of the logical definitions.

**Comment by NCIEVS** [comment]
Ahhh!  Yes, that's right.
