### ISSUE TITLE
Tag 105 - Lucene Search -Query Type- Start With Does not Return specific Search Results

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#87]
Steps to reproduce:
1) launch server and client protege5
2)Use Eric user and Login to "https://nciws-d699-v.nci.nih.gov:9090" 
3) In  Add Basic Query use the following search criteria:
Property = Label
Query Type = Start with
Value = "L"
4) Click Search and it returns all categories instead of specific criteria related.   

Note: This issue occurs on other query type as well..
Please see attached screen shot for more details.

Regards,
Reza
![lucene search_startwith_tag 105](https://cloud.githubusercontent.com/assets/8367102/20446587/6b936a4e-ada8-11e6-8a94-769ef5164834.png)

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106)

**Comment by rmehri** [comment]
Hi, 
I have updated the latest edit tab plugin and retested the fix. I still don't see specific search results using "Start With" in some cases. It returns combination results.  Please see attached video clip for more details. 

[Tag105_Retested_Fix.zip](https://github.com/NCIEVS/nci-protege5/files/616967/Tag105_Retested_Fix.zip)
Thanks,
Reza

**Comment by bdionne** [comment]
Are you running the new [nci-0.106](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.106) tag?

Did you select "starts with token" or "starts with string"?

**Comment by NCIEVS** [comment]
Need to note that "starts with - string" is case-insensitive, but "exact match - string" is case-sensitive.

Will open a separate issue for case-sensitivity of the exact string search for an enhancement & future release.

**Comment by rmehri** [comment]
I have used "starts with - string" and retested this fix successfully.  This ticket is closed. 
Thanks,
Reza
